/**
 * `npm run abi:gen` -- regenerates src/chain/abi.generated.ts from the compiled
 * Laxu contracts in ../Contracts/artifacts. Run it after every contract change
 * (`npx hardhat compile` in Contracts/ first): the backend's call and event
 * signatures then come from the same build that was deployed.
 *
 * Pure file transform -- no network, no chain.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ARTIFACTS = resolve(__dirname, "../../Contracts/artifacts/contracts");
const OUT = resolve(__dirname, "../src/chain/abi.generated.ts");

/// Contract name -> exported constant.
const CONTRACTS: Array<[string, string]> = [
  ["PositionToken", "positionTokenAbi"],
  ["PositionTokenFactory", "positionTokenFactoryAbi"],
  ["LendingPool", "lendingPoolAbi"],
  ["LendingPoolFactory", "lendingPoolFactoryAbi"],
  ["LendingVault", "lendingVaultAbi"],
  ["PerplReader", "perplReaderAbi"],
];

function main(): void {
  const parts = [
    "// GENERATED by scripts/genAbi.ts from ../Contracts/artifacts -- do not edit by hand.",
    "// Regenerate with `npm run abi:gen` after recompiling the contracts.",
    "",
  ];
  for (const [contract, name] of CONTRACTS) {
    const path = join(ARTIFACTS, `${contract}.sol`, `${contract}.json`);
    const artifact = JSON.parse(readFileSync(path, "utf8")) as { abi: unknown[] };
    parts.push(`export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;`, "");
    console.log(`${contract}: ${artifact.abi.length} entries`);
  }
  writeFileSync(OUT, parts.join("\n"));
  console.log(`wrote ${OUT}`);
}

main();
