/**
 * `npm run abi:gen` -- regenerates src/lib/abi.generated.ts from the compiled
 * Laxu contracts in ../Contracts/artifacts. Run it after every contract change
 * (`npx hardhat compile` in Contracts/ first), so the App's calls and reads
 * come from the same build that was deployed. The backend does the same.
 *
 * Pure file transform: no network, no chain.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const ARTIFACTS = resolve(here, "../../Contracts/artifacts/contracts");
const OUT = resolve(here, "../src/lib/abi.generated.ts");

/** Contract name -> exported constant. */
const CONTRACTS = [
  ["PositionToken", "positionTokenAbi"],
  ["PositionTokenFactory", "positionTokenFactoryAbi"],
  ["LendingPool", "lendingPoolAbi"],
  ["LendingVault", "lendingVaultAbi"],
  ["PerplReader", "perplReaderAbi"],
];

const parts = [
  "// GENERATED by scripts/genAbi.mjs from ../Contracts/artifacts -- do not edit by hand.",
  "// Regenerate with `npm run abi:gen` after recompiling the contracts.",
  "",
];
for (const [contract, name] of CONTRACTS) {
  const artifact = JSON.parse(readFileSync(join(ARTIFACTS, `${contract}.sol`, `${contract}.json`), "utf8"));
  parts.push(`export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;`, "");
  console.log(`${contract}: ${artifact.abi.length} entries`);
}
writeFileSync(OUT, parts.join("\n"));
console.log(`wrote ${OUT}`);
